# Generated by Django 3.2 on 2021-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20210506_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='student/images'),
        ),
    ]
