# Generated by Django 3.2 on 2021-05-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20210512_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='profile1.jpg', null=True, upload_to='student/images'),
        ),
    ]
