# Generated by Django 3.2 on 2021-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20210602_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project_guide',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
